Repository jyjyjy25/Coding-Test-Study, pull requests merged in 2023-10, with the labels that each got.

#11 [김지윤] 3주차 제출
  week3/04-1 버블 정렬/015 수 정렬하기 1/김지윤.py
  week3/04-1 버블 정렬/016 버블 정렬 프로그램 1/김지윤.py
  week3/04-2 선택 정렬/017 내림차순으로 자릿수 정렬하기/김지윤.py
  week3/04-3 삽입 정렬/018 ATM 인출 시간 계산하기/김지윤.py
  week3/04-4 퀵 정렬/019 K번째 수 구하기/김지윤.py
  week3/04-5 병합 정렬/020 수 정렬하기 2/김지윤.py
  week3/04-5 병합 정렬/021 버블 정렬 프로그램 2/김지윤.py
  week3/04-6 기수 정렬/022 수 정렬하기 3/김지윤.py
Labels: 정렬

#12 [장지인] 3주차 제출
  week3/04-1 버블 정렬/015 수 정렬하기 1/장지인.py
  week3/04-1 버블 정렬/016 버블 정렬 프로그램 1/장지인.py
  week3/04-2 선택 정렬/017 내림차순으로 자릿수 정렬하기/장지인.py
  week3/04-3 삽입 정렬/018 ATM 인출 시간 계산하기/장지인.py
  week3/04-4 퀵 정렬/019 K번째 수 구하기/장지인.py
  week3/04-5 병합 정렬/020 수 정렬하기 2/장지인.py
  week3/04-5 병합 정렬/021 버블 정렬 프로그램 2/장지인.py
  week3/04-6 기수 정렬/022 수 정렬하기 3/장지인.py
  장지인.py
Labels: 정렬

#14 [이미라] 4주차 제출
  week4/05-1 깊이 우선 탐색/023 연결 요소의 개수 구하기/.gitkeep
  week4/05-1 깊이 우선 탐색/023 연결 요소의 개수 구하기/이미라.py
  week4/05-1 깊이 우선 탐색/024 신기한 소수 찾기/.gitkeep
  week4/05-1 깊이 우선 탐색/024 신기한 소수 찾기/이미라.py
  week4/05-1 깊이 우선 탐색/025 친구 관계 파악하기/.gitkeep
  week4/05-1 깊이 우선 탐색/025 친구 관계 파악하기/이미라.py
  week4/05-2 너비 우선 탐색/026 DFS와 BFS 프로그램/.gitkeep
  week4/05-2 너비 우선 탐색/026 DFS와 BFS 프로그램/이미라.py
  week4/05-2 너비 우선 탐색/027 미로 탐색하기/.gitkeep
  week4/05-2 너비 우선 탐색/027 미로 탐색하기/이미라.py
  week4/05-2 너비 우선 탐색/028 트리의 지름 구하기/.gitkeep
  week4/05-2 너비 우선 탐색/028 트리의 지름 구하기/이미라.py
Labels: DFS/BFS

#15 [김지윤] 4주차 제출
  week4/05-1 깊이 우선 탐색/023 연결 요소의 개수 구하기/.gitkeep
  week4/05-1 깊이 우선 탐색/023 연결 요소의 개수 구하기/김지윤.py
  week4/05-1 깊이 우선 탐색/024 신기한 소수 찾기/.gitkeep
  week4/05-1 깊이 우선 탐색/024 신기한 소수 찾기/김지윤.py
  week4/05-1 깊이 우선 탐색/025 친구 관계 파악하기/.gitkeep
  week4/05-1 깊이 우선 탐색/025 친구 관계 파악하기/김지윤.py
  week4/05-2 너비 우선 탐색/026 DFS와 BFS 프로그램/.gitkeep
  week4/05-2 너비 우선 탐색/026 DFS와 BFS 프로그램/김지윤.py
  week4/05-2 너비 우선 탐색/027 미로 탐색하기/.gitkeep
  week4/05-2 너비 우선 탐색/027 미로 탐색하기/김지윤.py
  week4/05-2 너비 우선 탐색/028 트리의 지름 구하기/.gitkeep
  week4/05-2 너비 우선 탐색/028 트리의 지름 구하기/김지윤.py
  week4/05-2 너비 우선 탐색/트리의 지름 구하기/.gitkeep
Labels: DFS/BFS

#18 [장지인] 5주차 제출
  week5/05-3 이진 탐색/029 원하는 정수 찾기/.gitkeep
  week5/05-3 이진 탐색/029 원하는 정수 찾기/장지인.py
  week5/05-3 이진 탐색/030 블루레이 만들기/.gitkeep
  week5/05-3 이진 탐색/030 블루레이 만들기/장지인.py
  week5/05-3 이진 탐색/031 배열에서 K번째 수 찾기/.gitkeep
  week5/05-3 이진 탐색/031 배열에서 K번째 수 찾기/장지인.py
  week5/06-1 그리디 알고리즘/032 동전 개수의 최솟값 구하기/.gitkeep
  week5/06-1 그리디 알고리즘/032 동전 개수의 최솟값 구하기/장지인.py
  week5/06-1 그리디 알고리즘/033 카드 정렬하기/.gitkeep
  week5/06-1 그리디 알고리즘/033 카드 정렬하기/장지인.py
  week5/06-1 그리디 알고리즘/034 수를 묶어서 최댓값 만들기/.gitkeep
  week5/06-1 그리디 알고리즘/034 수를 묶어서 최댓값 만들기/장지인.py
  week5/06-1 그리디 알고리즘/035 회의실 배정하기/.gitkeep
  week5/06-1 그리디 알고리즘/035 회의실 배정하기/장지인.py
  week5/06-1 그리디 알고리즘/036 최솟값을 만드는 괄호 배치 찾기/.gitkeep
  week5/06-1 그리디 알고리즘/036 최솟값을 만드는 괄호 배치 찾기/장지인.py
Labels: 탐색, 그리디
